name: CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # Define the operating systems you want to run the job on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      #- name: Install gtest manually
      #  run: sudo apt-get install libgtest-dev

      #- name: Install benchmark manually
      #  run: |
      #      git clone https://github.com/google/benchmark.git
      #      git clone https://github.com/google/googletest.git benchmark/googletest
      #      cd benchmark
      #      cmake -E make_directory "build"
      #      cmake -E chdir "build" cmake -DCMAKE_BUILD_TYPE=Release ../
      #      cmake --build "build" --config Release
      #      sudo cmake --build "build" --config Release --target install

      - uses: actions/checkout@v6

      - name: Get Cmake 4.X
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            choco install cmake
          else
            # get cmake 4
            test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
            sudo apt-get update
            sudo apt-get install cmake -y
          fi;
        shell: bash


      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type

        # The macro ${{github.workspace}} results in windows file seprators, (\) which CMake often cannot parse.
        # To get around this use a relative path instead.
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            export CXXFLAGS="/experimental:log"
            cmake -DTEST=ON -Dgtest_disable_pthreads=ON -B ./build
          else
            export CXXFLAGS="-fdiagnostics-format=sarif-file"
            cmake -DTEST=ON -B ${{github.workspace}}/build
          fi;
        shell: bash

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build

      - uses: actions/upload-artifact@v4
        with:
          name: sarif_file
          path: ./*.sarif

      - name: Test
        working-directory: ${{github.workspace}}/build/test
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest
